# -*- coding: utf-8 -*-
"""CCPD_CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANwePYmbhTU9XlNTlnAU2RhZSlOaZI1a
"""

from google.colab import drive
drive.mount('/content/drive')  # authorize when prompted

# === EDIT: the CCPD2019 folder that contains ccpd_fn / ccpd_challenge =========
ROOT = "/content/drive/MyDrive/LPR/LPR_data_sets/CCPD/CCPD2019"
DST  = "/content/drive/MyDrive/LPR/datasets/ccpd_yolo_nested"
# ==============================================================================

import os, glob, shutil, random
from PIL import Image
random.seed(42)

def parse_bbox(p):
    # filename ...-<bbox>-...  where <bbox> = x1&y1_x2&y2
    s = os.path.splitext(os.path.basename(p))[0].split('-')[2]
    (x1,y1),(x2,y2) = map(lambda q: tuple(map(int,q.split('&'))), s.split('_'))
    return x1,y1,x2,y2

def yolo_line(w,h,x1,y1,x2,y2,cls=0):
    cx=((x1+x2)/2)/w; cy=((y1+y2)/2)/h; bw=(x2-x1)/w; bh=(y2-y1)/h
    return f"{cls} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}\n"

fn_dir = os.path.join(ROOT, "ccpd_fn")
chal_dir = next((os.path.join(ROOT, n) for n in ["ccpd_challenge","ccpd_challange","ccpd_challanhe"]
                 if os.path.isdir(os.path.join(ROOT, n))), None)

fn_imgs = sorted(glob.glob(os.path.join(fn_dir, "**", "*.jpg"), recursive=True)) if os.path.isdir(fn_dir) else []
chal_imgs = sorted(glob.glob(os.path.join(chal_dir, "**", "*.jpg"), recursive=True)) if chal_dir else []

if not fn_imgs:
    raise SystemExit("ccpd_fn not found or empty. Check ROOT path.")

if chal_imgs:
    print(f"Train on ccpd_fn ({len(fn_imgs)}), validate on challenge ({len(chal_imgs)})")
    splits = {"train": fn_imgs, "val": chal_imgs}
else:
    print(f"No challenge folder found; doing 80/20 split inside ccpd_fn ({len(fn_imgs)} images).")
    random.shuffle(fn_imgs)
    cut = int(len(fn_imgs)*0.8)
    splits = {"train": fn_imgs[:cut], "val": fn_imgs[cut:]}

for s in ("train","val"):
    os.makedirs(os.path.join(DST, "images", s), exist_ok=True)
    os.makedirs(os.path.join(DST, "labels", s), exist_ok=True)

def write_split(imgs, split):
    skipped = 0
    for p in imgs:
        try:
            x1,y1,x2,y2 = parse_bbox(p)
            with Image.open(p) as im: w,h = im.size
            lbl = yolo_line(w,h,x1,y1,x2,y2)
            img_out = os.path.join(DST,"images",split,os.path.basename(p))
            lbl_out = os.path.join(DST,"labels",split,os.path.splitext(os.path.basename(p))[0]+".txt")
            if not os.path.exists(img_out):
                try: os.symlink(p, img_out)
                except OSError: shutil.copy2(p, img_out)
            with open(lbl_out, "w") as f: f.write(lbl)
        except Exception:
            skipped += 1
    print(f"{split}: wrote {len(imgs)-skipped} labels, skipped {skipped}")

write_split(splits["train"], "train")
write_split(splits["val"],   "val")

yaml_path = os.path.join(DST, "ccpd.yaml")
with open(yaml_path, "w") as f:
    f.write(f"path: {DST}\ntrain: images/train\nval: images/val\nnames: [plate]\n")
print("Wrote", yaml_path)

DST = "/content/drive/MyDrive/LPR/datasets/ccpd_yolo_nested"
!ls -lah "$DST/images/val" | head
!find "$DST/images/val" -type l | head -n 3   # shows a few symlinks
!find "$DST/images/val" -type f | wc -l       # count visible to the OS

import os, glob, random
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt

DST = "/content/drive/MyDrive/LPR/datasets/ccpd_yolo_nested"  # <-- edit if different
val_dir = os.path.join(DST, "images/val")
lbl_dir = os.path.join(DST, "labels/val")

imgs = sorted(glob.glob(os.path.join(val_dir, "*.jpg")))
assert imgs, f"No images found in {val_dir}"
img_path = random.choice(imgs)

# load image
img = Image.open(img_path).convert("RGB")
W, H = img.size

# load matching label
stem = os.path.splitext(os.path.basename(img_path))[0]
lbl_path = os.path.join(lbl_dir, stem + ".txt")
with open(lbl_path) as f:
    cls, cx, cy, w, h = map(float, f.read().split())

# denormalize YOLO [cx,cy,w,h] -> [x1,y1,x2,y2]
x1 = int((cx - w/2) * W); y1 = int((cy - h/2) * H)
x2 = int((cx + w/2) * W); y2 = int((cy + h/2) * H)

# draw box
draw = ImageDraw.Draw(img)
draw.rectangle([x1, y1, x2, y2], outline="red", width=3)

plt.imshow(img); plt.axis("off")
print("Image:", img_path)
print("Label:", open(lbl_path).read().strip())

"""Fine tuning yolo for plate detection"""

!pip -q install ultralytics
import os, torch
from ultralytics import YOLO

# Paths
DST = "/content/drive/MyDrive/LPR/datasets/ccpd_yolo_nested"   # your dataset folder
yaml_path = f"{DST}/ccpd.yaml"                                  # created earlier
project   = "/content/drive/MyDrive/LPR/runs"                   # <-- runs SAVED IN DRIVE
name      = "ccpd_yolov8n_1024"                                 # run name in Drive

import os, torch
assert os.path.exists(yaml_path), f"Missing: {yaml_path}"

from ultralytics import YOLO
model = YOLO("yolov8n.pt")  # COCO-pretrained detector

# Train (writes to: {project}/{name}/...)
results = model.train(
    data=yaml_path,
    imgsz=1024, epochs=50, batch=-1,
    device=0 if torch.cuda.is_available() else "cpu",
    workers=2, lr0=3e-3, cos_lr=True, patience=10, cache=True,
    project=project, name=name, exist_ok=True
)

print(f"Best weights: {project}/{name}/weights/best.pt")
print(f"Last weights: {project}/{name}/weights/last.pt")

!pip -q install ultralytics
from ultralytics import YOLO

best = "/content/drive/MyDrive/LPR/runs/ccpd_yolov8n_1024/weights/best.pt"
yaml_path = "/content/drive/MyDrive/LPR/datasets/ccpd_yolo_nested/ccpd.yaml"

model = YOLO(best)                 # <-- loads your fine-tuned weights
model.val(data=yaml_path, imgsz=1024)

!pip -q install ultralytics
from ultralytics import YOLO
import os, glob, random, cv2
from google.colab.patches import cv2_imshow

# --- EDIT these paths if yours differ -----------------------------------------
DST      = "/content/drive/MyDrive/LPR/datasets/ccpd_yolo_nested"          # dataset root
WEIGHTS  = "/content/drive/MyDrive/LPR/runs/ccpd_yolov8n_1024/weights/best.pt"  # fine-tuned model
SPLIT    = "val"     # change to "train" to sample from the training set
OUT_DIR  = "/content/drive/MyDrive/LPR/runs/sample_preds"                   # where to save outputs
IMGSZ    = 1024
CONF     = 0.25
# ------------------------------------------------------------------------------

# 1) Pick a random image from the split
img_dir = os.path.join(DST, "images", SPLIT)
imgs = sorted(glob.glob(os.path.join(img_dir, "*.jpg")))
assert imgs, f"No images found in {img_dir}"
img_path = random.choice(imgs)
print("Using image:", img_path)

# 2) Load model and run prediction
model = YOLO(WEIGHTS)                   # loads your CCPD-finetuned detector
res = model.predict(source=img_path, imgsz=IMGSZ, conf=CONF, iou=0.6,
                    max_det=2, verbose=False)[0]

# 3) Show annotated result inline
annot = res.plot()                      # BGR image with boxes drawn
cv2_imshow(cv2.cvtColor(annot, cv2.COLOR_BGR2RGB))

# 4) Save annotated image and a top-1 crop to Drive
os.makedirs(OUT_DIR, exist_ok=True)
stem = os.path.splitext(os.path.basename(img_path))[0]
out_img = os.path.join(OUT_DIR, f"{stem}_pred.jpg")
cv2.imwrite(out_img, annot)

if res.boxes is not None and len(res.boxes) > 0:
    x1,y1,x2,y2 = map(int, res.boxes.xyxy[0].tolist())   # top-1 by confidence
    im = cv2.imread(img_path)
    crop = im[max(y1,0):max(y2,0), max(x1,0):max(x2,0)]
    crop_path = os.path.join(OUT_DIR, f"{stem}_crop.jpg")
    cv2.imwrite(crop_path, crop)
    print("Saved:", out_img, "and", crop_path)
else:
    print("Saved:", out_img, "(no detections; try lower CONF or larger IMGSZ)")





